# CI de Nível 01 - Disparo manual a partir de 1(um) clique

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# trigger usada: workflow_dispatch

on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs

jobs:
  e2e-testes:

  #maquina que o job vai executar
  runs-on:  ubuntu-latest

  # passos do script de build
  steps:
    # clone projeto
    - uses: actions/checkout@v4

    # instalação do node
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x

    # instalação yarn
    - name: Instalando Yarn
      run: npm install -g yarn

    # instalando dependencias 
    - name: Instalando dependências
      run:  yarn

    # instalação do Playwright 
    - name: Instalando o Playwright
      run: yarn playwright install

    # executar os testes 
    - name: Executando Testes E2E
      run: yarn e2e