# CI de nível 3 - Disparo após conclusão de uma pipeline
name: 'Execução por Deploy'

# regras para disparo 
# gatilho a partir de outro pipe = workflow_run

on:
  workflow_run:
    workflows:  ['Execução Manual']
    types:
      - completed

jobs:
  e2e-testes:
    runs-on: ubuntu-latest

    #  condicional if
    # `${expressão}`

    if: ${{ github.event.workflow_run.conclusion  ==  'success' }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instala Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando o Playwright
        run: yarn playwright install

      - name: Executando Testes E2E
        run: yarn e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled()  }}
        with:
          name: relatorio
          path: ./playwright-report